version: "3.1"

services:
  odoo_app:
    container_name: odoo_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:8069:8069'

  odoo_db:
    container_name: odoo_db
    image: postgres:15
    restart: always
    volumes:
      - odoo_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "127.0.0.1:5432:5432"

volumes:
  odoo_postgres:
    driver: local
